public class Triangle {

//     List<Engine__c> engines = [
//     SELECT Name
//     FROM Engine__c
//     LIMIT 50000
//     ];


// Map<String, Object> uniqueRecordsByEngine = new Map<String, Object>();
// Map<String, Object> forDelete = new Map<String, Object>();

// for (Engine__c engine : engines) {
//     if (!uniqueRecordsByEngine.containsKey(engine.Name)) {
//         uniqueRecordsByEngine.put(engine.Name, engine);
//     } else {
//         forDelete.put(engine.Name, engine);
//     }    
// }


//     List<Auto__c> autos = [
//     SELECT Name
//     FROM Auto__c
//     LIMIT 50000
//     ];

// Map<String, Object> uniqueRecordsAutos = new Map<String, Object>();

// for (Auto__c auto : autos) {
//     if (!uniqueRecordsByAutos.containsKey(auto.Name)) {
//         uniqueRecordsByAutos.put(auto.Name, auto);
//     } else {
//         forDelete.put(auto.Name, auto);
//     }   
// }

//     List<Detail__c> details = [
//     SELECT Name
//     FROM Detail__c
//     LIMIT 50000
//     ];


// Map<String, Object> uniqueRecordsByDetails = new Map<String, Object>();

// for (Detail__c detail : details) {
//     if (!uniqueRecordsByDetails.containsKey(detail.Name)) {
//         uniqueRecordsByDetails.put(detail.Name, detail);
//     } else {
//         forDelete.put(detail.Name, detail);
//     }   
// }

}